### ISSUE TITLE
export Vector2

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#21]
```
 @exports
  output: Vector2 = Vector2.ZERO;
```
gets turned into
```
export(Vector2Constructor) var output = Vector2.ZERO
```
which doesn't work.
Might need some special rule.

**Comment by johnfn** [comment]
Ah darn it, good catch.

**Comment by ksjogo** [comment]
Weirdly that doesn't seem to happen in the tests and only when running over a project.
Not sure what could cause that difference.

**Comment by johnfn** [comment]
Basically the reason for that is that the tests don't import ALL of our generated .d.ts files, because that is an immense number of definitions that would slow tests down. Instead they use an extremely simplified .d.ts that has the base definitions along with stubs for Vector2 and Vector3.

https://github.com/johnfn/ts2gd/blob/main/generate_library_defs/generate_base.ts#L257

We have to generate definitions for Vector2, Vector3 and a handful of other base classes in a special way to allow the user to do `Vector2()` to be the same as `new Vector2()` and I didn't end up changing the stub test definitions to handle that. 

Just fixed this in https://github.com/johnfn/ts2gd/blob/main/generate_library_defs/generate_base.ts#L257 - and I made the definitions for Vector2 a little more accurate so that they'd show this error.

**Comment by ksjogo** [comment]
Ahh, got it.
Is the performance hit due to every test spinning up its own ts compiler?

**Comment by johnfn** [comment]
That's exactly right. That and the Godot definition files are currently ~70K lines of code, which seems like a lot when you just want to run a single 3 line test. :-)

**Comment by ksjogo** [comment]
Yeah, that doesn't sound too great with 140 tests.
I am wondering if there would be some way to spin up once and generate once and then kind of diff the file tree instead. (Essentially snapshot testing like storybooks https://storybook.js.org/docs/react/workflows/snapshot-testing)

**Comment by johnfn** [comment]
Yeah, in theory it should be possible to test everything without spawning tons of TS compilers. Some thoughts.

One possibility: run a single instance of the compiler, concatenate all tests into one big blob, compile the whole thing, and diff. I've avoided it so far because there are a lot of edge cases that feel tricky to me - earlier tests could cause later tests to break, and it'd be hard to work out what the issue was.

Another possibility would simply be to keep the compiler running, but instead of running a huge blob of tests, just get it to compile files one at a time. This is probably possible but I haven't dived deep into the TS compiler to know how to do it! 

Running the entire test suite on my laptop takes around a second right now so it hasn't bothered me enough to get me to research this more thoroughly :-) and you can always add the flag `only` to a test to run only that test, speeding things up even more. BUT I'm totally open to PRs on this!

**Comment by ksjogo** [comment]
Yeah, it is really quick at the moment, so not worth spending too much time there yet.
Only thing I think is suboptimal is that some types will differ in the testing environment compared to full and the tests won't catch these (like the Vector stuff).

**Comment by johnfn** [comment]
Yeah totally. I should just copy over the other custom type definitions so we don't run into that in the future.
