### ISSUE TITLE
increment operator extraneous code

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#28]
```
this.ticks++;
```
currently generates 
```
    self.ticks
    self.ticks += 1
```
With godot complaining `(STANDALONE_EXPRESSION): Standalone expression (the line has no effect).gdscript(7)`
I suppose we could skip the first line.

**Comment by johnfn** [comment]
Yes, that's true. 

The reason we emit the useless line right now is that some of the time we need the return value from `this.ticks++`, and writing the code to determine if we need it or not is a little tricky to get right. On the other hand, the current code is *always* right, though sometimes it generates a pointless expression :-) 

Actually, now that I type it out, it's not *that* hard to validate, we just need to check our parent and make sure it's a statement rather than a subexpression...

**Comment by johnfn** [comment]
Fixed with 2ed71834cbb11ddafd90ed7edb68489702fa557d
