### ISSUE TITLE
script to generate _godot_defs

### ISSUE THREAD

**Issue by ksjogo** [johnfn/ts2gd#38]
https://github.com/johnfn/ts2gd/commit/c31b2aab83c6a23ed646fba30c06a78dda9c20f8 had some changes related to the _godot_defs, but the changed defs weren't included.
Trying to generate these to fix, I ran into the situation of this repo not having some ts2gd.json to run on for generation of these.
Should we include a small godot project, so that we can run the command?

**Comment by johnfn** [comment]
Yeah - that would be great. Embarrassingly, the way I've been doing it so far is just to copy and paste from my personal project. The reason it's a little annoying to do is because you need a clone of the godot engine repo in order to build the definitions. Maybe I could include it as a submodule...

**Comment by ksjogo** [comment]
Created a PR going in the direction of doing that.
(With indeed a submodule)

We could probably even write some action that creates them automatically and creates an PR every month or so.

**Comment by johnfn** [comment]
Thats awesome. Actually the best time to do it would be whenever we publish a new version. I currently use `npm run auto-publish` for that, so we could just toss in a "generate _godot_defs" into that script.
